### ISSUE TITLE
Allow usage with Posts.

### ISSUE THREAD

**Issue by lezama** [simison/back-to-the-theme#3]
Right now the drop down only offers pages, maybe it should just be a url?

**Comment by simison** [comment]
PR welcome :-) 

It's prolly a fairly simple [WP_Query](https://codex.wordpress.org/Class_Reference/WP_Query) to gather posts and pages into one list and since it gives you IDs that you can use as values for `<option>`, you wouldn't need to change anything else about the script.

**Comment by simison** [comment]
BOOM! https://github.com/simison/back-to-the-theme/pull/5
